version: '3'
services:
  notebook:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - NB_UID=1000
    command: start.sh jupyter lab
